Вывод в консоль прогресса загрузки страницы
starkhv70/backend-project-lvl3 pull request #10
Opened 2021-08-09 05:48 UTC by starkhv70

C помощью библиотеки [Listr](https://github.com/SamVerschueren/listr) реализовал вывод в консоль процесса загрузки страницы. Задача #6

2021-08-10 10:18 UTC, foofaev requested changes

2021-08-10 10:18 UTC, foofaev commented on src/page-loader.js
> +      const listr = new Listr(tasks, { concurrent: true });
Листр по умолчанию прерывает все таски, если одна закончилась неудачей. А у нас по заданию надо, чтобы таски все проходили. Надо или гасить ошибки на загрузке, или добавить в параметры листра exitOnError: false

2021-08-10 23:44 UTC, starkhv70 commented on src/page-loader.js
> +      const listr = new Listr(tasks, { concurrent: true });
добавил параметр  exitOnError: false

2021-08-10 23:47 UTC, starkhv70 commented on src/page-loader.js
> +      const listr = new Listr(tasks, { concurrent: true });
но с этим параметром упали тесты Хекслета

2021-08-11 11:21 UTC, starkhv70 commented on src/page-loader.js
> +      const listr = new Listr(tasks, { concurrent: true });
все победил, вернул exitOnError: false. Проблемма была с режимом recursive: true у функции mkdir. Это не проходило тесты. И еще ошибки линтера в своих тестах поправил

2021-08-12 09:22 UTC, foofaev approved these changes

2021-08-12 09:22 UTC, merged