Issue#2
starkhv70/backend-project-lvl3 pull request #8
Opened 2021-03-24 01:35 UTC by starkhv70

Реализовал загрузку изображений и локальных ресурсов из тегов link и script. 
Fixes #2 , Fixes #3

2021-03-25 19:41 UTC, foofaev requested changes
Все очень круто. Немного порефакторим только

2021-03-25 19:41 UTC, foofaev commented on src/util.js
> +  });
Тут направление верное. Но надо чуть-чуть порефакторить
Мы тут два раза подряд делаем одно и то же - получаем attrName, получаем урлу, получаем ноду в доме.
То есть, можно разложить на этапы.
Например:

```
tagName.toArray().map(element => $(element)).filter(проверка, что у атрибута есть наш тег).map($element => ({$element, url: new URL}).filter({url} => url.origin === origin)

```

2021-03-25 19:41 UTC, foofaev commented on src/util.js
> +    .flatMap((tagName) => $(`${tagName}`).toArray()
бессмысленная обертка в ковычки

2021-03-25 19:41 UTC, foofaev commented on src/util.js
> +  const resources = tagsWithResources.map((tag) => {
из-за того, что в теле функции мы делаем сайд эффект, ` $(tag).attr(attrName, relativeFilepath)`, то мап не идеоматичен. Тут правильнее использовать forEach, собирать массив, используя [].push

2021-03-25 19:41 UTC, foofaev commented on src/util.js
> +export const processingResources = (origin, htmlData, resourceDir) => {
это функция основной логики. наверно, стоит ее вернуть в index

2021-03-26 06:45 UTC, starkhv70 commented on src/util.js
> +export const processingResources = (origin, htmlData, resourceDir) => {
я бы хотел её оставить в util.js Мне нравится, что в индексе реализована основная логика pageLoader, а все вспомогательные функции перенесены в util. В моей логике это вспомогательная функция. Но если ты считаешь, что код будет понятнее я перенесу. Со стороны всегда виднее)

2021-03-26 11:50 UTC, starkhv70 commented on src/util.js
> +    .flatMap((tagName) => $(`${tagName}`).toArray()
исправил

2021-03-27 12:03 UTC, starkhv70 commented on src/util.js
> +  const resources = tagsWithResources.map((tag) => {
переделал на Foreach

2021-03-27 12:04 UTC, starkhv70 commented on src/util.js
> +  });
поменял

2021-03-27 19:25 UTC, foofaev requested changes

2021-03-27 19:25 UTC, foofaev commented on bin/page-loader.js
> +  .action((pageUrl) => pageLoader(new URL(pageUrl), program.output));
логики в бинарнике быть не должно
парсинг урлы - логика

2021-03-27 19:25 UTC, foofaev commented on src/util.js
> +export const processingResources = (origin, htmlData, resourceDir) => {
Ну так-то эта функция неотделима от основной логики. Это не абсолютная абстракция, которая делает что-то абсолютно нейтральное. Мне кажется, надо в основной, но делай на свое усмотрение

2021-03-28 10:35 UTC, starkhv70 commented on src/util.js
> +export const processingResources = (origin, htmlData, resourceDir) => {
Да, давай перенесу. Твое предложение тоже обоснованно. В этой функции много логики основной.

2021-03-28 10:49 UTC, starkhv70 commented on bin/page-loader.js
> +  .action((pageUrl) => pageLoader(new URL(pageUrl), program.output));
изменил, перенес парсинг адреса в код функции `pageLoader`

2021-03-28 10:49 UTC, starkhv70 commented on src/util.js
> +export const processingResources = (origin, htmlData, resourceDir) => {
перенес

2021-03-29 21:18 UTC, foofaev approved these changes

2021-03-29 21:18 UTC, merged