Добавил отладку в проект
starkhv70/backend-project-lvl3 pull request #9
Opened 2021-07-11 16:56 UTC by starkhv70

Реализовал режим отладки в проекте c использованием библиотеки [debug](https://github.com/visionmedia/debug ). Задача #4

2021-07-16 10:36 UTC, foofaev requested changes

2021-07-16 10:36 UTC, foofaev commented on src/page-loader.js
>        .map((tag) => {
$(tag) нам нужен в коде два раза. Есть смысл его сразу сохранить вместо просто tag. И потом забирать $tag.attr(1), $tag.attr(2)

2021-07-16 10:36 UTC, foofaev commented on src/page-loader.js
> +  log('Page %s will be download to %s', link, pageFilepath);
ниже мы все это дублируем. Может, лучше описать, что мы делаем? Это же дебаг, лучше описывать конкретные действия кода, чтобы было понятно, где проблема возникла. Например, тут мы первым делом пытаемся создать директорию (кстати, стоит добавить проверку, вдруг, директория уже существует)

2021-07-16 10:36 UTC, foofaev commented on src/page-loader.js
> +  log('Page %s will be download to %s', link, pageFilepath);
воткнуть бы еще дебаг, какие данные мы получили в саму функцию, с чем мы работаем

2021-07-17 13:47 UTC, starkhv70 commented on src/page-loader.js
>        .map((tag) => {
я не очень понял, что ты имеешь ввиду.
Вот так например?
``` js
const tag = $(tag);
....
return {tag, url};
```

2021-07-17 21:08 UTC, foofaev commented on src/page-loader.js
>        .map((tag) => {
Ага

2021-08-04 05:58 UTC, starkhv70 commented on src/page-loader.js
> +  log('Page %s will be download to %s', link, pageFilepath);
сделал

2021-08-05 08:00 UTC, starkhv70 commented on src/page-loader.js
>        .map((tag) => {
поменял

2021-08-08 14:24 UTC, foofaev approved these changes

2021-08-08 14:24 UTC, merged